#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-packagecloud-wagon
Version  : 0.0.6
Release  : 2
URL      : https://github.com/computology/maven-packagecloud-wagon/archive/maven-packagecloud-wagon-0.0.6.tar.gz
Source0  : https://github.com/computology/maven-packagecloud-wagon/archive/maven-packagecloud-wagon-0.0.6.tar.gz
Source1  : https://repo.maven.apache.org/maven2/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6/maven-packagecloud-wagon-0.0.6.jar
Source2  : https://repo.maven.apache.org/maven2/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6/maven-packagecloud-wagon-0.0.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-packagecloud-wagon-data = %{version}-%{release}

%description
# Packagecloud Maven Wagon
### NOTE: this is currently in beta
## Usage
**Visit [packagecloud.io/api_token](packagecloud.io/api_token) and get your API token before proceeding.**

%package data
Summary: data components for the mvn-maven-packagecloud-wagon package.
Group: Data

%description data
data components for the mvn-maven-packagecloud-wagon package.


%prep
%setup -q -n maven-packagecloud-wagon-maven-packagecloud-wagon-0.0.6

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6/maven-packagecloud-wagon-0.0.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6/maven-packagecloud-wagon-0.0.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6/maven-packagecloud-wagon-0.0.6.jar
/usr/share/java/.m2/repository/io/packagecloud/maven/wagon/maven-packagecloud-wagon/0.0.6/maven-packagecloud-wagon-0.0.6.pom
